# Dependencies
highlighter:      rouge

lsi: false
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax

# Permalinks
permalink:        pretty
gems:
   - jekyll-paginate

# Setup
title:            Wizecore
tagline:          Corporate site
description:      Gazorpazorp approved.
url:              https://wizecore.com
baseurl:          /

author:
  name:           Huksley
  url:            http://гайнутдинов.рф

paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.0

excerpt_separator: <!--more-->

github:
  repo:           https://github.com/wizecore
