# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
gems:			        [ jekyll-paginate, jekyll-gist ]

# Setup
title:            Wizecore
tagline:          Corporate site
description:      Gazorpazorp approved.
url:              https://wizecore.com
baseurl:          /

author:
  name:           Huksley
  url:            http://гайнутдинов.рф

paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.0

github:
  repo:           https://github.com/wizecore
